sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1008611asd

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8xQd7HBmmaruW1hCJT
    access-key-secret: YLlHOb1LAksoCgc0gv0eNXFBXUH4KM
    bucket-name: green-5522

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  wechat:
    app-id: wx1cc049fe10bdf87f
    secret: e806b0be28402bfa6cbe2d7c20ac2934
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://2a5478b8.r34.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://2a5478b8.r34.cpolar.top/refundSuccess